Repository volcano-sh/dashboard, pull requests merged in 2024-11, with the labels that each got.

#4 Add OWNERS file
  OWNERS
Labels: lgtm, size/XS, retest-not-required-docs-only

#3 fixed logo visibility issue on the bottom part of the left panel
  frontend/src/assets/logo.svg
  frontend/src/assets/volcano-icon-color.svg
  frontend/src/components/Layout.jsx
  volcanoLogo.png
Labels: lgtm, size/XS, approved

#5 Add deployment file and user guide
  .gitignore
  README.md
  backend/.travis.yml
  backend/Dockerfile
  backend/src/server.js
  deployment/build/backend/Dockerfile
  deployment/build/frontend/Dockerfile
  deployment/volcano-dashboard.yaml
  frontend/Dockerfile
  frontend/nginx.conf
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/volcano-icon-color.svg
  frontend/src/assets/logo.svg
  frontend/src/components/Charts/JobStatusPieChart.jsx
  frontend/src/components/Charts/QueueResourcesBarChart.jsx
  frontend/src/components/Dashboard.jsx
  frontend/src/components/Jobs.jsx
  frontend/src/components/Layout.jsx
  frontend/src/components/Pods.jsx
  frontend/src/components/Queues.jsx
  frontend/src/config/api.js
  volcanoLogo.png
Labels: lgtm, approved, size/XL

#7 pagination pod and job from cache
  backend/src/server.js
  deployment/volcano-dashboard.yaml
  frontend/src/components/Jobs.jsx
  frontend/src/components/Pods.jsx
  frontend/src/components/Queues.jsx
  frontend/src/components/utils.js
Labels: lgtm, approved, size/L
