Repository volcano-sh/dashboard, pull requests merged in 2025-03, with the labels that each got.

#51 Format whole codebase
  .prettierignore
  backend/.babelrc
  backend/package-lock.json
  backend/package.json
  backend/src/server.js
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Charts/JobStatusPieChart.jsx
  frontend/src/components/Charts/PodStatusLineChart.jsx
  frontend/src/components/Charts/QueueResourcesBarChart.jsx
  frontend/src/components/Charts/StatCard.jsx
  frontend/src/components/Charts/chartConfig.js
  frontend/src/components/Dashboard.jsx
  frontend/src/components/Jobs.jsx
  frontend/src/components/Layout.jsx
  frontend/src/components/Pods.jsx
  frontend/src/components/Queues.jsx
  frontend/src/components/SearchField.jsx
  frontend/src/components/utils.js
  frontend/src/config/api.js
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/theme.js
  frontend/vite.config.js
Labels: size/XXL, lgtm, approved

#50 Removed package-lock.json from individual workspaces
  CONTRIBUTING.md
  backend/package-lock.json
  frontend/package-lock.json
  package-lock.json
Labels: size/XXL, lgtm, approved

#34 update sidebar ui/ux
  frontend/src/components/Layout.jsx
Labels: lgtm, approved, size/M

#52 fix deprecated package #46
  backend/.babelrc
  backend/package.json
  package-lock.json
Labels: size/XXL, lgtm, approved

#55 Refactored Frontend: Modularized UI into Components
  frontend/src/App.jsx
  frontend/src/components/Jobs.jsx
  frontend/src/components/Pods.jsx
  frontend/src/components/Queues.jsx
  frontend/src/components/jobs/JobDialog.jsx
  frontend/src/components/jobs/JobFilters.jsx
  frontend/src/components/jobs/JobPagination.jsx
  frontend/src/components/jobs/JobSearchBar.jsx
  frontend/src/components/jobs/JobStatusChip.jsx
  frontend/src/components/jobs/JobTable.jsx
  frontend/src/components/jobs/JobTableHeader.jsx
  frontend/src/components/jobs/Jobs.jsx
  frontend/src/components/pods/PodDetailsDialog.jsx
  frontend/src/components/pods/Pods.jsx
  frontend/src/components/pods/PodsPagination.jsx
  frontend/src/components/pods/PodsTable.jsx
  frontend/src/components/pods/SearchBar.jsx
  frontend/src/components/queues/QueuePagination.jsx
  frontend/src/components/queues/QueueTable.jsx
  frontend/src/components/queues/QueueToolbar.jsx
  frontend/src/components/queues/QueueYamlDialog.jsx
  frontend/src/components/queues/Queues.jsx
Labels: size/XXL, lgtm, approved

#65 fix/Backend server stopped working due to recent package upgrade
  backend/src/server.js
  package-lock.json
Labels: lgtm, approved, size/L

#60 Code reusability
  frontend/src/App.jsx
  frontend/src/components/Dashboard.jsx
  frontend/src/components/SearchField.jsx
  frontend/src/components/Searchbar.jsx
  frontend/src/components/Titlecomponent.jsx
  frontend/src/components/dashboard/ChartsContainer.jsx
  frontend/src/components/dashboard/Dashboard.jsx
  frontend/src/components/dashboard/DashboardHeader.jsx
  frontend/src/components/dashboard/ErrorDisplay.jsx
  frontend/src/components/dashboard/StatCardsContainer.jsx
  frontend/src/components/dashboard/utils.js
  frontend/src/components/jobs/Jobs.jsx
  frontend/src/components/pods/Pods.jsx
  frontend/src/components/queues/QueueTable.jsx
  frontend/src/components/queues/Queues.jsx
  package-lock.json
Labels: size/XXL, lgtm, approved

#53 Fix/44 Add tests
  backend/package.json
  backend/src/server.js
  backend/tests/server.test.js
  backend/tests/setupTests.js
  backend/vitest.config.js
  frontend/.gitignore
  frontend/eslint.config.js
  frontend/package.json
  frontend/playwright.config.js
  frontend/src/components/Layout.jsx
  frontend/tests/Layout.test.jsx
  frontend/tests/setupTests.js
  frontend/vitest.config.js
  package-lock.json
  package.json
Labels: size/XXL, lgtm, approved
